backend:
  name: github
  repo: APata7/portfolio
  branch: main
  base_url: https://sveltia-cms-auth.antoniopata7.workers.dev
  auth_endpoint: auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "paginas"
    label: "Conteúdos do Site"
    files:
      - file: "data/sobre.json"
        label: "Sobre mim"
        name: "sobre"
        fields:
          - label: "Texto"
            name: "texto"
            widget: "text"

      - file: "data/destaques.json"
        label: "Destaques"
        name: "destaques"
        fields:
          - label: "Lista de destaques"
            name: "items"
            widget: "list"
            fields:
              - label: "Destaque"
                name: "texto"
                widget: "string"

      - file: "data/experiencia.json"
        label: "Experiência"
        name: "experiencia"
        fields:
          - label: "Experiências"
            name: "items"
            widget: "list"
            fields:
              - { label: "Ano", name: "ano", widget: "string" }
              - { label: "Cargo", name: "cargo", widget: "string" }
              - { label: "Entidade", name: "empresa", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text" }

      - file: "data/competencias.json"
        label: "Competências"
        name: "competencias"
        fields:
          - label: "Competências"
            name: "items"
            widget: "list"
            fields:
              - { label: "Competência", name: "texto", widget: "string" }

      - file: "data/formacao.json"
        label: "Formação"
        name: "formacao"
        fields:
          - label: "Formações"
            name: "items"
            widget: "list"
            fields:
              - { label: "Ano", name: "ano", widget: "string" }
              - { label: "Curso", name: "curso", widget: "string" }
              - { label: "Entidade", name: "entidade", widget: "string" }

      - file: "data/projetos.json"
        label: "Projetos"
        name: "projetos"
        fields:
          - label: "Projetos"
            name: "items"
            widget: "list"
            fields:
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text" }

      - file: "data/disponivel.json"
        label: "Disponível para"
        name: "disponivel"
        fields:
          - label: "Serviços"
            name: "items"
            widget: "list"
            fields:
              - { label: "Serviço", name: "titulo", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text" }
